"""Agent schemas — PlannerAgent input/output contracts."""

from datetime import datetime
from uuid import UUID, uuid4

from typing import Any

from pydantic import Field, model_validator

from app.schemas.common import (
    DSRABaseModel,
    ResearchDepth,
    SearchQuery,
    SourceType,
)


class ResearchGoal(DSRABaseModel):
    """
    Input to PlannerAgent.
    Created from user API request and stored at session start.
    """
    session_id: UUID
    topic: str = Field(..., min_length=3, max_length=500)
    depth: ResearchDepth = ResearchDepth.NORMAL
    max_sources_per_query: int = Field(default=10, ge=1, le=50)
    source_preferences: list[SourceType] = Field(
        default_factory=lambda: list(SourceType)
    )
    focus_areas: list[str] = Field(default_factory=list)
    language: str = Field(default="en", pattern=r"^[a-z]{2}$")


class ResearchPlan(DSRABaseModel):
    """
    Output of PlannerAgent.
    Contains all search queries and metadata for the research session.
    """
    session_id: UUID
    topic: str
    queries: list[SearchQuery] = Field(..., min_length=1)
    estimated_complexity: float = Field(ge=0.0, le=1.0)
    suggested_depth: ResearchDepth
    focus_areas: list[str] = Field(default_factory=list)
    reasoning: str = Field(..., min_length=10)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PlannerSearchQuery(DSRABaseModel):
    """LLM-facing planner query payload without runtime-generated identifiers."""
    query_text: str = Field(..., min_length=3, max_length=300)
    source_type: SourceType
    priority: float = Field(default=1.0, ge=0.0, le=1.0)
    filters: dict = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def normalize_llm_aliases(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data

        normalized = dict(data)
        if "query_text" not in normalized and "query" in normalized:
            normalized["query_text"] = normalized["query"]
        if "source_type" not in normalized and "engine" in normalized:
            normalized["source_type"] = normalized["engine"]
        normalized.pop("id", None)
        return normalized


class PlannerLLMPlan(DSRABaseModel):
    """
    LLM-facing PlannerAgent response.
    Session identity is owned by the application, not generated by the model.
    """
    queries: list[PlannerSearchQuery] = Field(..., min_length=1)
    estimated_complexity: float = Field(ge=0.0, le=1.0)
    suggested_depth: ResearchDepth
    focus_areas: list[str] = Field(default_factory=list)
    reasoning: str = Field(..., min_length=10)
