# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
# timezone =

# max length of characters to encode to slug.
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported
# when formatting the version file location.
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# version path separator; as above, this can be a space, a comma,
# or a newline. defaults to a space.
# version_path_separator = :

# the URL of the database. This is overridden in env.py
sqlalchemy.url = postgresql://dsra_user:change-this-password@localhost:5432/dsra_v2

[post_write_hooks]
# post_write_hooks defines scripts or methods that are run
# after generating a new revision file.

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
